/**
	Generated by sails-inverse-model
	Date:Thu Nov 22 2018 12:17:02 GMT-0400 (Hora estándar oeste, Sudamérica)
*/

module.exports = {
  attributes: {
    fecha: {
      type: 'ref',
      columnType: 'date'
        },
    detalle: {
      type: 'string',
    },
    ref: {
      type: 'string',
    },
    debe: {
      type: 'number',
    },
    haber: {
      type: 'number',
    },
    idCuenta : {
      model : 'cuenta'
    },
    idLibroDiario : {
      model : 'librodiario'
    }
  }
};
