/**
	Generated by sails-inverse-model
	Date:Thu Nov 22 2018 12:20:03 GMT-0400 (Hora estándar oeste, Sudamérica)
*/

module.exports = {
  attributes: {
    nombre: {
      type: 'string',
    },
    nit: {
      type: 'number',
    },
    idUsuario:{
      model : 'usuario'
    },
    planDeCuenta: {
      collection: 'plandecuenta',
      via: 'idEmpresa',
    }
  }
};
