/**
	Generated by sails-inverse-model
	Date:Thu Nov 22 2018 12:17:37 GMT-0400 (Hora estándar oeste, Sudamérica)
*/

module.exports = {
    attributes: {
        detalle: {
            type: 'string',
        },
        fecha: {
            type: 'ref',
            columnType: 'date',
            required: true
        },
        idPlanDeCuenta: {
            model: 'plandecuenta'
        },
        asientos : {
            collection : 'asiento',
            via :'idLibroDiario'
        }
    }
};