/**
	Generated by sails-inverse-model
	Date:Thu Nov 22 2018 11:54:50 GMT-0400 (Hora estándar oeste, Sudamérica)
*/

module.exports = {
    attributes: {
        name: {
            type: 'string',
            required: true
        },
        owner: {
            type: 'string',
        }
    }
};