/**
	Generated by sails-inverse-model
	Date:Thu Nov 22 2018 12:06:58 GMT-0400 (Hora estándar oeste, Sudamérica)
*/

module.exports = {
    attributes: {
        nombre: {
            type: 'string',
            required: true
        },
        numero: {
            type: 'string',
        }
    }
};